NightmareTranslation = {
 Skill_JapaneseToEnglish : function (e) {
    var t = e;
    var ee = ("undefined" != typeof reactHotLoaderGlobal && reactHotLoaderGlobal.default.signature, t.WPNName = ["楽器", "魔書", "魔具", "祈祷", "刀剣", "打撃", "射出", "長柄"]);
    ae = t.WPNName_en = ["Instrument", "Tome", "Focus", "Staff", "Blade", "Hammer", "Ranged", "Polearm"];
    if (t.indexOf("劣勢") >= 0) t = t.replace(new RegExp("味方前衛全員のスキル攻撃の効果が(.*)。\\s※劣勢時のみ、コンボチャンス時のみ有効。"), "$1 the effect of attack skills for all front-line allies when at a disadvantage and when comboing."), t = t.replace("特大増加", "Massively increases"), t = t.replace("大増加", "Greatly increases"), t = t.replace("増加", "Moderately increases");
    else if (t.indexOf("有利属性") >= 0) t = t.replace(new RegExp("^(.*)での有利属性ダメージ効果が(.*)。\\s※(.*)の場合のみ有効。"), "$3 take $2 $1."), t = t.replace("敵が火属性", "Fire-type enemies"), t = t.replace("敵が風属性", "Wind-type enemies"), t = t.replace("敵が水属性", "Water-type enemies"), t = t.replace("火属性", "Fire damage"), t = t.replace("風属性", "Wind damage"), t = t.replace("水属性", "Water damage"), t = t.replace("特大増加", "massively-increases"), t = t.replace("大増加", "greatly-increases"), t = t.replace("増加", "moderately-increases");
    else if (t.indexOf("補助") >= 0) t.indexOf("※") > 0 && (t = t.replace("※コロシアム残り時間が2分未満になると、その時点でこの召喚スキルは終了する。", "※Effect ends early if two minutes or less remaining for Colosseum.")), t = t.replace(new RegExp("敵全体の補助スキル発動率が(.*)。"), "$1 the hit rate of Colosseum Aid skills for all enemies."), t = t.replace(new RegExp("味方全体の補助スキル発動率が(.*)。"), "$1 the hit rate of Colosseum Aid skills for all allies."), t = t.replace("超特大減少", "Colossal decreases"), t = t.replace("特大減少", "Massively decreases"), t = t.replace("大減少", "Greatly decreases"), t = t.replace("減少", "Moderately decreases"), t = t.replace("特大増加", "Massively increases"), t = t.replace("大増加", "Greatly increases"), t = t.replace("増加", "Moderately increases");
    else if (t.indexOf("SP") >= 0) t = t.replace(new RegExp("味方全体のSPを(\\d+)%回復。"), "Restore $1% SP to Everyone."), t = t.replace(new RegExp("味方前衛ジョブ全体のSPを(\\d+)%回復。"), "Restore $1% of max SP for all allies with vanguard/attack jobs."), t = t.replace(new RegExp("味方後衛ジョブ全体のSPを(\\d+)%回復。"), "Restore $1% of max SP for all allies with backline/support jobs."), t = t.replace(new RegExp("味方全体の(.*)の消費SPが(.*)。"), "$2 the SP cost of $1 for all allies."), t = t.replace("全属性スキル", "all skills"), t = t.replace("火属性スキル", "Fire skills"), t = t.replace("風属性スキル", "Wind skills"), t = t.replace("水属性スキル", "Water skills"), t = t.replace("特大軽減", "Massively reduce"), t = t.replace("大軽減", "Greatly reduce"), t = t.replace("軽減", "Moderately reduce");
    else if (t.indexOf("スキルのうち") >= 0) t = t.replace(new RegExp("(.*?)武器スキルのうち、HP回復とデバフ効果が(.*?)し、ダメージとバフ効果が(.*?)するが、敵から受ける(.*?)ダメージも(.*?)。"), "$2 $1 Weapon Skills that recover HP & debuffs, $3 $1 Weapon Skills that give damage & buffs while $5 damage taken from $4 damage."), t = t.replace(/火属性/g, "Fire-type"), t = t.replace(/風属性/g, "Wind-type"), t = t.replace(/水属性/g, "Water-type"), t = t.replace(/超特大増加/g, "Colossal increases"), t = t.replace(/特大増加/g, "Massively increases"), t = t.replace(/大増加/g, "Greatly increases"), t = t.replace(/増加/g, "Moderately increases");
    else if (t.indexOf("HP") >= 0) t.indexOf("スキル効果") >= 0 ? (t = t.replace(new RegExp("(.*)の敵が使用するHP回復スキル効果が(.*)かつ(.*)ダメージスキル効果も減少。"), "$2 the effectiveness of enemy $1 HP Recovery skills while reducing the $3 damage inflicted by enemies."), t = t.replace("特大減少", "Massively reduce"), t = t.replace("大減少", "Greatly reduce"), t = t.replace("減少", "Moderately reduce"), t = t.replace(/火属性/g, "Fire"), t = t.replace(/風属性/g, "Wind"), t = t.replace(/水属性/g, "Water")) : (t = t.replace(new RegExp("HP(\\d+)%以上で受けた致死ダメージをHP1状態で耐える。"), "If over $1% HP, allies will survive with 1 HP when hit by a lethal attack."), t = t.replace(new RegExp("味方全体のHPを(\\d+)%回復。"), "Restore $1% of max HP for all surviving allies."));
    else {
        if (t = t.replace(new RegExp("※このスキルは「(.*?)」として扱う。"), ""), t.indexOf("※") > 0 && (t = t.replace("※特定の討伐イベントで当召喚スキルを使用しても敵がカウンター攻撃をしない。", "※When Summoned, prevents Trigger of enemy counter."), t = t.replace("※物理、魔法両方適用されます。", ""), t = t.replace("※ダメージ系スキルのみ有効。", ""), t = t.replace(new RegExp("※さらに対象が(.*)減少状態の場合、減少量に応じて効果が上昇。"), "※Greater Effect with Lower Allies Stacks."), t = t.replace(new RegExp("※さらに対象が(.*)上昇状態の場合、上昇量に応じて効果が上昇。"), "※Greater Effect with Higher Enemy Stacks."), t = t.replace("※味方のイノチが敵の1/2以下になると、その時点でこの召喚スキルは終了する。", "※Effect ends when allies' inochi(lifeforce) is 1/2 or lower than enemy's inochi(lifeforce)."), t = t.replace("※敵が召喚スキルを使用していない場合、失敗する。", "※Fails if No Nightmare is Summoned after the Call."), t = t.replace("※敵が召喚スキル準備中、および使用していない場合、失敗する。", "")), t.indexOf("スキル効果") >= 0 || t.indexOf("スキルの効果") >= 0) t.indexOf("増加") >= 0 ? (t = t.replace(new RegExp("(.*)効果が(.*)するが、敵から受ける(.*)も増加"), "$2 the effect of $1, while increasing the $3 inflicted by enemies"), t = t.replace(new RegExp("味方全体の(.*)の効果が(.*)。"), "$2 the effectiveness of $1 for all allies."), t = t.replace(new RegExp("味方が使用する(.*?)でのスキル効果が(.*?)。"), "$2 the Effectiveness of $1 Skills."), t = t.replace("僅かに増加", "Slightly increases"), t = t.replace("超特大増加", "Colossal increases"), t = t.replace("特大増加", "Massively increases"), t = t.replace("大増加", "Greatly increases"), t = t.replace("増加", "Moderately increases"), t = t.replace("火属性の武器スキル", "Fire skills"), t = t.replace("風属性の武器スキル", "Wind skills"), t = t.replace("水属性の武器スキル", "Water skills"), t = t.replace("火属性スキル", "Fire skills"), t = t.replace("風属性スキル", "Wind skills"), t = t.replace("水属性スキル", "Water skills"), t = t.replace("全ての属性スキル", "All-Element weapon skills"), t = t.replace("火属性ダメージ", "Fire damage"), t = t.replace("風属性ダメージ", "Wind damage"), t = t.replace("水属性ダメージ", "Water damage"), ee.map(function (e, a) {
            t = t.replace(e, ae[a])
        })) : (t = t.replace("敵が使用している効果時間のある召喚スキルの効果と効果時間をコピーする", "When the Enemy is using a Nightmare with an Active Timer, Copy it's Skill Effects & Skill Duration"), t = t.replace(new RegExp("敵の使用した(.*)効果が(.*)。 "), "$2 the effectiveness of enemy $1."), t = t.replace(new RegExp("敵が使用する(.*)と(.*)でのスキル効果が(.*)。"), "$3 the effectiveness of enemy $1 and $2 skills."), t = t.replace(new RegExp("敵が使用する(.*)でのスキル効果が(.*)。"), "$2 the effectiveness of enemy $1 skills."), ee.map(function (e, a) {
            t = t.replace(e, ae[a])
        }), t = t.replace("火属性のスキル", "Fire attack skills"), t = t.replace("風属性のスキル", "Wind attack skills"), t = t.replace("水属性のスキル", "Water attack skills"), t = t.replace("超特大減少", "Colossively reduce"), t = t.replace("特大減少", "Massively reduce"), t = t.replace("大減少", "Greatly reduce"), t = t.replace("減少", "Moderately reduce"));
        else if (t.indexOf("味方") >= 0 || 0 == t.indexOf("生存者")) t = t.replace(new RegExp("味方前衛生存者の(.*)が(.*)。"), "$2 $1 for all surviving front-line allies."), t = t.replace(new RegExp("味方生存者の(.*)が(.*)。"), "$2 $1 for all surviving allies."), t = t.replace(new RegExp("生存者の(.*)が(.*)。"), "$2 $1 for all surviving allies."), t = t.replace("超特大上昇", "Colossively raise"), t = t.replace("特大上昇", "Massively raise"), t = t.replace("大上昇", "Greatly raise"), t = t.replace("上昇", "Moderately raise");
        else if (t.indexOf("敵") >= 0) t = t.replace("敵の準備中、または効果発動中の召喚スキルを最初から準備し直しさせる。", "If the Enemy team is using a Nightmare with an Active Countdown Timer, Rewind it to it's Standby State ※Fails if No Nightmare is Summoned after the Call."), t = t.replace(new RegExp("敵が使用している召喚スキルの準備中、効果時間中の時間を(.*)する。"), "If the Enemy team is using a Nightmare with an Active Countdown Timer, $1 the Preparation time or Active time for it."), t = t.replace("敵が次に準備を開始した召喚スキルの準備時間を1分30秒に変更する。", "Change the Preparation time for the Enemy's  Next Nightmare to 1m30s."), t = t.replace(new RegExp("敵全体の(.*)が(.*)。"), "$2 $1 for all enemies."), t = t.replace(new RegExp("気絶者含む敵前衛全員の(.*)が(.*)。"), "$2 $1 for all front-line enemies, including KO'ed ones."), t = t.replace("特大減少", "Massively lower"), t = t.replace("大減少", "Greatly lower"), t = t.replace("減少", "Moderately lower"), t = t.replace("特大短縮", "Massively shortens"), t = t.replace("大短縮", "Greatly shortens");
        else {
            var a = "装備セット変更の使用回数がリセットされる",
                n = "Reset the Number of times Sets can be changed";
            t = t.replace("前衛の" + a, n + " for Vanguard"), t = t.replace("後衛の" + a, n + " for Backline"), t = t.replace(a, n), t = t.replace("次に使う召喚スキルの準備時間を5秒に変更する。", "Change the Preparation time for the Next Nightmare to 5 Seconds.")
        }
        t = t.replace("物理、及び魔法攻撃力", "attack (physical and magical)"), t = t.replace("物理、及び魔法防御力", "defense (physical and magical)"), t = t.replace("物理攻撃力", "physical attack"), t = t.replace("物理防御力", "physical defense"), t = t.replace("魔法攻撃力", "magical attack"), t = t.replace("魔法防御力", "magical defense"), t = t.replace("攻撃力", "attack (physical and magical)"), t = t.replace("防御力", "defense (physical and magical)")
    }
    return t = t.replace(/。/g, ".")
  }
}

module.exports = { 
  NightmareTranslation
}